version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  php:
    image: wodby/drupal-php:7.1-3.0.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
      #      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
      #      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
      COLUMNS: 80
    volumes:
      - .:/var/www/html:cached

  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.1
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/htdocs/web
    volumes:
      - .:/var/www/html:cached
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=HostRegexp:{subdomain:[A-Za-z0-9-]+}.dc2018-react-backend.docker.localhost,dc2018-react-backend.docker.localhost"

  adminer:
    image: wodby/adminer:4.3-1.1.0
    environment:
      ADMINER_SALT: adminer-salt
    labels:
      - "traefik.backend=adminer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:adminer.drupal.docker.localhost"

  solr:
    image: wodby/drupal-solr:8-6.6-2.2.0
    environment:
      SOLR_HEAP: 1024m
    labels:
      - "traefik.backend=solr"
      - "traefik.port=8983"
      - "traefik.frontend.rule=Host:solr.drupal.docker.localhost"
    volumes:
      - ./solr:/opt/solr/server/solr/mycores:cached
      - ./htdocs/web/modules/contrib/search_api_solr/solr-conf/6.x:/opt/solr/server/solr/configsets/drupal/conf:cached

  mailhog:
    image: mailhog/mailhog
    labels:
      - "traefik.backend=mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailhog.drupal.docker.localhost"

  memcached:
    image: wodby/memcached:1.4-2.0.0

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:portainer.drupal.docker.localhost"

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
